Added comparation of input data of phone and address
gecmenow/OnlineMarket pull request #4
Opened 2021-05-03 18:51 UTC by gecmenow

Regex added to class BuyerInfoChecker.

2021-05-04 16:27 UTC, serhii-shkodenko requested changes
В этой ветке должен быть код только для четвертого задания. Мы это обсуждали на встречах. Раздели код, пожалуйста, по соответвующим ПРам. Если нужна будет помощь - пиши.

2021-05-12 22:48 UTC, serhii-shkodenko reviewed
Я проверил методы для проверки номеров телефонов и адресов. Они работают. Аппрув для ПР будет после мержа третьего занятия, потому что там возможны изменения.

2021-06-11 07:02 UTC, serhii-shkodenko requested changes
Регулярные выражение проверил, они работают. Поправь эти замчения, и вмерж мастер после мержа третьего ПР. После этого я еще раз гляну, но на первый взгляд, все Ок.

2021-06-11 07:02 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/OrderService.cs
> +            var valid = _checker.CheckPhone(input);
Достаточно просто `if(_checker.CheckPhone(input))`.

Ты результат работы метода пишешь в переменную c именем `valid`. Поэтому я предлагаю так метод и переназвать: `IsPhoneNumberValid(input)` или вообще `IsPhoneNumber(input)`. Тогда уcловное выражение выше будет хорошо к тому же читаться.

2021-06-11 20:23 UTC, serhii-shkodenko commented
Вмержи пожалуйста main.

2021-06-11 20:35 UTC, gecmenow commented
Вмержил main

2021-06-11 20:38 UTC, serhii-shkodenko requested changes

2021-06-11 20:38 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Interfaces/ICheckerService.cs
> +        public bool CheckPhone(string input);
Удали, пожалуйста, модификатор. По умолчанию, все члены интерфейсов публичные. Пэтому их опускают.

2021-06-11 20:38 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Interfaces/ICheckerService.cs
> +        public bool CheckAddress(string input);
Удали, пожалуйста, модификатор. По умолчанию, все члены интерфейсов публичные. Пэтому их опускают.

2021-06-11 20:38 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Interfaces/IOrderService.cs
> +        bool IsAddressValid(string number);
Тогда зачем тебе `ICheckerService`? Оставь либо одно, либо другое.

2021-06-11 20:49 UTC, gecmenow commented
В общем, когда написал, что вмержил, оказывается не вмержило. Видимо я что-то напутал, сейчас всё должно быть с main как и там. Комментарии учёл.

2021-06-11 20:57 UTC, serhii-shkodenko requested changes

2021-06-11 20:57 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Interaction/BuyerInteraction.cs
> +<<<<<<< HEAD
Смержил не очень корректно. Стянись и проверь. Кажется это не будет билдиться.

2021-06-11 20:59 UTC, gecmenow commented on KramDeliverFoodCompleted/Interaction/BuyerInteraction.cs
> +<<<<<<< HEAD
у меня забилдилось и я проверил программу, сейчас гляну файл и поправлю

2021-06-11 21:05 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Interaction/BuyerInteraction.cs
> +<<<<<<< HEAD
Нет, не билдится.
![Screenshot 2021-06-12 000505](https://user-images.githubusercontent.com/69808191/121748574-e9a94800-cb11-11eb-855b-74dccd30fb91.png)

2021-06-11 21:10 UTC, gecmenow commented on KramDeliverFoodCompleted/Interaction/BuyerInteraction.cs
> +<<<<<<< HEAD
Поправил новые мерж конфликты в других файлах

2021-06-11 21:13 UTC, serhii-shkodenko requested changes

2021-06-11 21:13 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CheckerService.cs
> +        public bool CheckPhone(string number)
Лучше назвать как-то с `IsValid`, как у тебя были названы другие методы, которые ты удалил.

2021-06-11 21:13 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CheckerService.cs
> +        public bool CheckAddress(string address)
Лучше назвать как-то с `IsValid` в имени, как у тебя были названы другие методы, которые ты удалил.

2021-06-11 21:17 UTC, gecmenow commented on KramDeliverFoodCompleted/Service/CheckerService.cs
> +        public bool CheckPhone(string number)
Переназвал, как было ранее в order IsPhoneValid

2021-06-11 21:17 UTC, gecmenow commented on KramDeliverFoodCompleted/Service/CheckerService.cs
> +        public bool CheckAddress(string address)
Переназвал, как было ранее в order IsAddressValid

2021-06-11 21:19 UTC, serhii-shkodenko requested changes
Поправь, пожалуйста, и будет апрув.

2021-06-11 21:19 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/OrderService.cs
> +            _checker = checker;
Кажется, эта зависимость больше не нужна, удали ее пожалуйста.

2021-06-11 21:23 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-06-11 21:25 UTC, merged