Task 5
gecmenow/OnlineMarket pull request #5
Opened 2021-05-19 12:26 UTC by gecmenow

Добавил логгирование в файл. Для удобства поиска, класс Называется Reporter, находится в папке Interaction. Идёт запись в файл id товара, т.к. кол-во на складе не добавлял, учитывается дата и время в файле, а для названия файла - дата.

2021-06-01 18:50 UTC, serhii-shkodenko requested changes
Регулярные выражения проверил, они работают, есть небольшие замечания. После их исправления и мержа третьего задания будет апрув.

2021-06-01 18:50 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Check/BuyerInfoChecker.cs
> +    public class BuyerInfoChecker
Поскольку этот класс содержить только статические методы, его лучше тоже обозначить статическим.

2021-06-01 18:50 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Check/BuyerInfoChecker.cs
> +            var expression = new Regex(pattern, RegexOptions.Compiled);
Опция `RegexOptions.Compiled` имеет смысл, когда объект `Regex()` является переиспользуемым. В твоей ситуации ты не получишь улучшение производительности. Поэтому либо удали, либо найди, пожалуйста, вариант с переиспользованием.

2021-06-01 18:50 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Check/BuyerInfoChecker.cs
> +            var expression = new Regex(pattern, RegexOptions.Compiled);
Опция `RegexOptions.Compiled` имеет смысл, когда объект `Regex()` является переиспользуемым. В твоей ситуации ты не получишь улучшение производительности. Поэтому либо удали, либо найди, пожалуйста, вариант с переиспользованием.

2021-06-01 18:59 UTC, serhii-shkodenko requested changes

2021-06-01 18:59 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Interaction/Reporter.cs
> +    public class Reporter
Классы, осуществляющие логирование принято называть `Logger` или как-то созвучно. Разработчик, который увидит твой класс `Reporter`, может не понять без детального с ним ознакомления, что он делает. Поэтому еголучше переназвать. 

Если бы ты не написал, что твой логер называется `Reporter`, я бы подумал, что он создает какие-то репорты, например, о статистике продаж или вроде того.

2021-06-01 18:59 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Interaction/Reporter.cs
> +        public void OrderedProduct(Product product)
Согласно [конвенции](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods), имена методов должны содержать в себе глагол.

2021-06-01 18:59 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Interaction/Reporter.cs
> +        public void AddedProduct(Product product)
Согласно [конвенции](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods), имена методов должны содержать в себе глагол.

2021-06-01 18:59 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Interaction/Reporter.cs
> +        public void AddedProduct(Product product)
Если тебе потребуется логировать какую-то другую информацию (а тебе потребуется), что тебе придется делать новые методы (исходя выбранного тобой подхода). Поэтому методы, которые соуществляют логирование делают максимально общими. 

Будет лучше сделать так, чтобы тебе не пришлось каждый раз писать новый метод для логирования, отличающийся по сути только именем.

2021-06-09 21:46 UTC, serhii-shkodenko commented
Зарезолви, пожалуйста, комментарии, которые ты поправил.

2021-06-11 20:39 UTC, serhii-shkodenko commented
Вмержи, пожалуйста, мейн.

2021-06-11 22:08 UTC, gecmenow commented
Вмержил main. Я убрал интерфейс ICheckerService и соответствующий Сервис. Перенёс эти методы в OrderService и сделал приватными, так я посчитал, что и данные будут сохранятся и проверка проходить будет успешно.

2021-06-12 18:39 UTC, serhii-shkodenko requested changes
Поправь небольшое замечание и будет апрув.

2021-06-12 18:39 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/LoggerService.cs
> +            var folderName = "Data";
Вынеси это в приватную константу.

2021-06-12 22:46 UTC, serhii-shkodenko approved these changes
На будущее - приватные константы обычно все равно называют в PascalCase.

Выглядит хорошо, можно мержить.

2021-06-13 07:40 UTC, merged

2021-06-13 07:41 UTC, gecmenow commented
Спасибо, в коде поправил имя константы.