Task 7
gecmenow/OnlineMarket pull request #7
Opened 2021-06-10 05:31 UTC by gecmenow

Added CacheServices, new classes - CacheService, CurrerncyExchangeService, Cache.
interfaces - ICache, ICacheService, CurrerncyExchangeService.

2021-06-14 12:50 UTC, serhii-shkodenko commented
Пофикси, пожалуйста, мерж конфликты.

2021-06-28 16:56 UTC, gecmenow commented
Fixed merge conflicts

2021-07-11 14:47 UTC, serhii-shkodenko requested changes

2021-07-11 14:47 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CacheService.cs
> +                    _cache.CacheData.RemoveAt(4);
Наверное надо удалять самый старый элемент кеша. Это будет самый первый элемент в коллекции, а не последний.

2021-07-11 14:47 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CacheService.cs
> +                if (_cache.CacheData.Count() != 0)
Поскольку ты здесь пользуешься списком, воспользуся его свойством `Count`, а не методом `Enumerable.Count()`.

2021-07-11 14:47 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CacheService.cs
> +                    while (_cache.CacheData.Count() < 5)
Здесь аналогично.

2021-07-11 14:47 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CacheService.cs
> +                IList<Product> data = default;
Эту и слудющую строку можно объединить: 
`return default`.

2021-07-11 14:47 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CacheService.cs
> +                _cache.CacheData.Remove(data);
А что будет если такого элемента нет в кеше? И как ты определеяшь его наличие, ведь речь идет о ссылочном типе, а значит два объекта с одинаковыми полями будут считаться разными, если у них разные ссылки.

2021-09-02 20:51 UTC, serhii-shkodenko requested changes
Поправь эти замечания и будет апрув.

2021-09-02 20:51 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CacheService.cs
> +                    _cache.CacheData.RemoveAt(1);
Индексы начинаются с "0". Если ты хочешь удалить самый первй элемент, используй `RemoveAt(0)`.

2021-09-02 20:51 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CacheService.cs
> +                if (_cache.CacheData.Count != 0)
Весь код внутри лока можно переписать так:

`return _cache.CacheData.Any() ? _cache.CacheData : default;
`
Проверять количество элементов в списке не имеет большого смысла, ты при добавлении уже проверил.

2021-09-02 20:51 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CacheService.cs
> +                if (_cache.CacheData.Equals(data))
Для того чтобы проверить, присутствует ли объект в списке, нужен метод `Contains().` Но для его корректно работы нужно реализовать `IEquatable<T>`. Будет проще проверить по `Id`.

2021-09-02 20:51 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/ProductService.cs
> +                AddToCacheDelegate addToCache = _cacheService.AddToCache;
Логичнее было бы использовать делегаты как параметры методов из `_cacheService`. Ну пусть пока так будет.

2021-09-06 09:26 UTC, serhii-shkodenko approved these changes
Виглядит хорошо. Можно мержить.

2021-09-06 09:49 UTC, merged