Task 8
gecmenow/OnlineMarket pull request #8
Opened 2021-06-10 05:33 UTC by gecmenow

Added converting summary, work maybe not done yet

2021-06-14 12:50 UTC, serhii-shkodenko commented
Пофикси, пожалуйста, мерж конфликты.

2021-07-11 14:59 UTC, serhii-shkodenko requested changes

2021-07-11 14:59 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Interfaces/ICurrerncyExchangeService.cs
> +            usd,
Имена членов enum должны быть именованы в PascalCase.

2021-07-11 14:59 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Interfaces/IData.cs
> +        Task<IList<ExchangeRate>> currencies { get; set; }
Имена свойств должны быть заданы в PascalCase.

2021-07-11 14:59 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Interfaces/IData.cs
> +        Task<IList<ExchangeRate>> currencies { get; set; }
И зачем ты хранишь таску? Храни список валют.

2021-07-11 14:59 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Interfaces/IOrderService.cs
> +        public bool SetPhoneNumber(string number);
Удали модификаторы доступа у методов. По умолчанию в интерфейсах они публичные и поэтому в явном виде не обозначаются. Это касается всех интерфейсов. Везду поудаляй, пожалуйста.

2021-07-11 14:59 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Models/Currency.cs
> +    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
В коде не должно быть закомментированных участков кода. Удали, пожалуйста.

2021-07-11 14:59 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CurrerncyExchangeService.cs
> +        //private string url = "https://api.privatbank.ua/p24api/exchange_rates?json&date=09.07.2021";
Удали этот закомментированный код, пожалуйста.

2021-07-11 14:59 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CurrerncyExchangeService.cs
> +                    //var tmp = articles.ExchangeRate.ToList();
Удали этот закмментированный код, пожалуйста.

2021-07-11 14:59 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CurrerncyExchangeService.cs
> +    public class CurrerncyExchangeService : ICurrerncyExchangeService
Этот класс у тебя называется так, что предполгает наличие методов для обмена валют, а он содержит лишь метод для получения списка валют. Поэтому его лучше переназвать. Конвертацию лучше сделать в бизнес слое.

2021-07-11 19:37 UTC, gecmenow commented on KramDeliverFoodCompleted/Service/CurrerncyExchangeService.cs
> +    public class CurrerncyExchangeService : ICurrerncyExchangeService
Метод переназвал. Я так понимаю, что речь скорее шла о диссериализации, вынес в класс OrderService.

2021-07-11 20:05 UTC, gecmenow commented
У меня гит показывает, что есть merge конфликты, но я их в студии почему-то не вижу. Может это какой-то глюк?

2021-07-11 21:09 UTC, serhii-shkodenko commented
> У меня гит показывает, что есть merge конфликты, но я их в студии почему-то не вижу. Может это какой-то глюк?

Если ты про панель git changes, там сообщение очень небольшое, его можно не заметить. Еще нужно находиться в нужной ветке.

2021-09-06 09:37 UTC, serhii-shkodenko requested changes
Есть парочка существенных замещаний по улучшению. Поправь их, пожалуйста.

2021-09-06 09:37 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/CurrerncyExchangeService.cs
> +                HttpResponseMessage response = await client.GetAsync("https://api.privatbank.ua/p24api/exchange_rates?json&date=09.07.2021");
А почему дата всегда одна и та же? Лучше динамически изменять этот параметр.

2021-09-06 09:37 UTC, serhii-shkodenko commented on KramDeliverFoodCompleted/Service/OrderService.cs
> +            var currencies = _currerncyExchangeService.GetCurrencies().Result;
Ты здесь используешь блокирующее ожидание. Удали его и используй асинхронный вызов.

2021-09-06 10:42 UTC, gecmenow commented on KramDeliverFoodCompleted/Service/CurrerncyExchangeService.cs
> +                HttpResponseMessage response = await client.GetAsync("https://api.privatbank.ua/p24api/exchange_rates?json&date=09.07.2021");
Проверял api и, видимо, забыл поменять. Исправил.

2021-09-06 12:14 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-09-07 16:25 UTC, merged